image: macos

branches:
  only:
    - master

environment:
  access_token:
    secure: 1Ep5ZXTk0f1AbqY1xVTGnHWDEEBnSm2RnlExqhH0AsAPS1cRYl9aJRHDonSioUOD

before_build:
- sudo pip install pandas

build_script:
- ./build.py

after_build:
- git config --global credential.helper store
- echo "https://${access_token}:x-oauth-basic@github.com" >> ~/.git-credentials
- git config --global user.email "32255369+chromezh@users.noreply.github.com"
- git config --global user.name "sgalal"
- mv data.sqlite3 ..
- git checkout gh-pages
- git clean -xdf
- mv ../data.sqlite3 .
- git add .
- |-
  if [ -n "$(git status --porcelain)" ]; then
    git commit -m "Deploy $APPVEYOR_REPO_COMMIT by AppVeyor"
    git push origin master
  fi
