#!/usr/bin/env python3

import sqlite3
import pandas

conn = sqlite3.connect('guangyun.sqlite3')
cur = conn.cursor()
cur.execute('''CREATE TABLE 'rhyme'
( 'id' INTEGER PRIMARY KEY
, 'tone' VARCHAR NOT NULL
, 'num_in_vol' VARCHAR NOT NULL
, 'name' VARCHAR NOT NULL
  CHECK
  ( tone IN ('平','上','去','入')
AND LENGTH(name) = 1
  )
);''')
cur.execute('''CREATE TABLE 'small_rhyme'
( 'id' INTEGER PRIMARY KEY
, 'of_rhyme' INTEGER NOT NULL REFERENCES 'rhyme'
, 'initial' VARCHAR NOT NULL
, 'rounding' VARCHAR NOT NULL
, 'division' VARCHAR NOT NULL
, 'upper_char' VARCHAR
, 'lower_char' VARCHAR
  CHECK
  ( LENGTH(initial) = 1
AND rounding IN ('O','C')
AND division IN ('1','2','3','4')
AND LENGTH(upper_char) = 1
AND LENGTH(lower_char) = 1
  )
);''')
cur.execute('''CREATE TABLE 'char_entity'
( 'id' INTEGER PRIMARY KEY
, 'of_small_rhyme' INTEGER NOT NULL REFERENCES 'small_rhyme'
, 'num_in_small_rhyme' VARCHAR NOT NULL
, 'name' VARCHAR NOT NULL
  CHECK (LENGTH(name) = 1)
);''')
cur.execute('CREATE INDEX idx_small_rhyme_upper_char on small_rhyme (upper_char);')
cur.execute('CREATE INDEX idx_small_rhyme_lower_char on small_rhyme (lower_char);')

data = pandas.read_csv('guangyun.csv', dtype={'C小韻內字序(不是Int)': 'str'})
cur.executemany('INSERT OR IGNORE INTO rhyme VALUES (?, ?, ?, ?)', zip(data['A韻序'], data['A聲調'], data['A韻名'], data['A韻(調整前)']))
cur.executemany('INSERT OR IGNORE INTO small_rhyme VALUES (?, ?, ?, ?, ?, ?, ?)', zip(data['B小韻序'], data['A韻序'], data['B紐'], data['B呼'], data['B等'], (i if i else None for i in data['B上字(null)']), (i if i else None for i in data['B下字(null)'])))
cur.executemany('INSERT INTO char_entity (of_small_rhyme, num_in_small_rhyme, name) VALUES (?, ?, ?)', zip(data['B小韻序'], data['C小韻內字序(不是Int)'], data['C字']))

cur.execute('''CREATE VIEW small_rhyme_view AS
SELECT id
  , tone
  , rhyme_name
  , rhyme
  , rhyme_pq
  , rhyme_pqr
  , CASE rhyme_pqr
      WHEN '東' THEN '通'
      WHEN '冬' THEN '通'
      WHEN '鍾' THEN '通'
      WHEN '江' THEN '江'
      WHEN '支' THEN '止'
      WHEN '脂' THEN '止'
      WHEN '之' THEN '止'
      WHEN '微' THEN '止'
      WHEN '魚' THEN '遇'
      WHEN '虞' THEN '遇'
      WHEN '模' THEN '遇'
      WHEN '齊' THEN '蟹'
      WHEN '佳' THEN '蟹'
      WHEN '皆' THEN '蟹'
      WHEN '灰' THEN '蟹'
      WHEN '咍' THEN '蟹'
      WHEN '祭' THEN '蟹'
      WHEN '泰' THEN '蟹'
      WHEN '夬' THEN '蟹'
      WHEN '廢' THEN '蟹'
      WHEN '真' THEN '臻'
      WHEN '諄' THEN '臻'
      WHEN '臻' THEN '臻'
      WHEN '文' THEN '臻'
      WHEN '欣' THEN '臻'
      WHEN '魂' THEN '臻'
      WHEN '痕' THEN '臻'
      WHEN '元' THEN '山'
      WHEN '寒' THEN '山'
      WHEN '桓' THEN '山'
      WHEN '刪' THEN '山'
      WHEN '山' THEN '山'
      WHEN '先' THEN '山'
      WHEN '仙' THEN '山'
      WHEN '蕭' THEN '效'
      WHEN '宵' THEN '效'
      WHEN '肴' THEN '效'
      WHEN '豪' THEN '效'
      WHEN '歌' THEN '果'
      WHEN '戈' THEN '果'
      WHEN '麻' THEN '假'
      WHEN '陽' THEN '宕'
      WHEN '唐' THEN '宕'
      WHEN '庚' THEN '梗'
      WHEN '耕' THEN '梗'
      WHEN '清' THEN '梗'
      WHEN '青' THEN '梗'
      WHEN '蒸' THEN '曾'
      WHEN '登' THEN '曾'
      WHEN '尤' THEN '流'
      WHEN '侯' THEN '流'
      WHEN '幽' THEN '流'
      WHEN '侵' THEN '深'
      WHEN '覃' THEN '咸'
      WHEN '談' THEN '咸'
      WHEN '鹽' THEN '咸'
      WHEN '添' THEN '咸'
      WHEN '咸' THEN '咸'
      WHEN '銜' THEN '咸'
      WHEN '嚴' THEN '咸'
      WHEN '凡' THEN '咸'
      ELSE NULL
    END AS 'class'
  , initial
  , [group]
  , place
  , rounding
  , rounding_han
  , division
  , division_han
  , upper_char
  , lower_char
  , fanqie
FROM
( SELECT small_rhyme.id
  , tone
  , num_in_vol || rhyme.name AS 'rhyme_name'
  , rhyme.name AS 'rhyme'
  , CASE rhyme.name
      WHEN '東' THEN '東'
      WHEN '董' THEN '東'
      WHEN '送' THEN '東'
      WHEN '冬' THEN '冬'
      WHEN '宋' THEN '冬'
      WHEN '鍾' THEN '鍾'
      WHEN '腫' THEN '鍾'
      WHEN '用' THEN '鍾'
      WHEN '江' THEN '江'
      WHEN '講' THEN '江'
      WHEN '絳' THEN '江'
      WHEN '支' THEN '支'
      WHEN '紙' THEN '支'
      WHEN '寘' THEN '支'
      WHEN '脂' THEN '脂'
      WHEN '旨' THEN '脂'
      WHEN '至' THEN '脂'
      WHEN '之' THEN '之'
      WHEN '止' THEN '之'
      WHEN '志' THEN '之'
      WHEN '微' THEN '微'
      WHEN '尾' THEN '微'
      WHEN '未' THEN '微'
      WHEN '魚' THEN '魚'
      WHEN '語' THEN '魚'
      WHEN '御' THEN '魚'
      WHEN '虞' THEN '虞'
      WHEN '麌' THEN '虞'
      WHEN '遇' THEN '虞'
      WHEN '模' THEN '模'
      WHEN '姥' THEN '模'
      WHEN '暮' THEN '模'
      WHEN '齊' THEN '齊'
      WHEN '薺' THEN '齊'
      WHEN '霽' THEN '齊'
      WHEN '祭' THEN '祭'
      WHEN '泰' THEN '泰'
      WHEN '佳' THEN '佳'
      WHEN '蟹' THEN '佳'
      WHEN '卦' THEN '佳'
      WHEN '皆' THEN '皆'
      WHEN '駭' THEN '皆'
      WHEN '怪' THEN '皆'
      WHEN '夬' THEN '夬'
      WHEN '灰' THEN '灰'
      WHEN '賄' THEN '灰'
      WHEN '隊' THEN '灰'
      WHEN '咍' THEN '咍'
      WHEN '海' THEN '咍'
      WHEN '代' THEN '咍'
      WHEN '廢' THEN '廢'
      WHEN '真' THEN '真'
      WHEN '軫' THEN '真'
      WHEN '震' THEN '真'
      WHEN '諄' THEN '諄'
      WHEN '準' THEN '諄'
      WHEN '稕' THEN '諄'
      WHEN '臻' THEN '臻'
      WHEN '文' THEN '文'
      WHEN '吻' THEN '文'
      WHEN '問' THEN '文'
      WHEN '欣' THEN '欣'
      WHEN '隱' THEN '欣'
      WHEN '焮' THEN '欣'
      WHEN '元' THEN '元'
      WHEN '阮' THEN '元'
      WHEN '願' THEN '元'
      WHEN '魂' THEN '魂'
      WHEN '混' THEN '魂'
      WHEN '慁' THEN '魂'
      WHEN '痕' THEN '痕'
      WHEN '很' THEN '痕'
      WHEN '恨' THEN '痕'
      WHEN '寒' THEN '寒'
      WHEN '旱' THEN '寒'
      WHEN '翰' THEN '寒'
      WHEN '桓' THEN '桓'
      WHEN '緩' THEN '桓'
      WHEN '換' THEN '桓'
      WHEN '刪' THEN '刪'
      WHEN '潸' THEN '刪'
      WHEN '諫' THEN '刪'
      WHEN '山' THEN '山'
      WHEN '產' THEN '山'
      WHEN '襇' THEN '山'
      WHEN '先' THEN '先'
      WHEN '銑' THEN '先'
      WHEN '霰' THEN '先'
      WHEN '仙' THEN '仙'
      WHEN '獮' THEN '仙'
      WHEN '線' THEN '仙'
      WHEN '蕭' THEN '蕭'
      WHEN '篠' THEN '蕭'
      WHEN '嘯' THEN '蕭'
      WHEN '宵' THEN '宵'
      WHEN '小' THEN '宵'
      WHEN '笑' THEN '宵'
      WHEN '肴' THEN '肴'
      WHEN '巧' THEN '肴'
      WHEN '效' THEN '肴'
      WHEN '豪' THEN '豪'
      WHEN '晧' THEN '豪'
      WHEN '号' THEN '豪'
      WHEN '歌' THEN '歌'
      WHEN '哿' THEN '歌'
      WHEN '箇' THEN '歌'
      WHEN '戈' THEN '戈'
      WHEN '果' THEN '戈'
      WHEN '過' THEN '戈'
      WHEN '麻' THEN '麻'
      WHEN '馬' THEN '麻'
      WHEN '禡' THEN '麻'
      WHEN '陽' THEN '陽'
      WHEN '養' THEN '陽'
      WHEN '漾' THEN '陽'
      WHEN '唐' THEN '唐'
      WHEN '蕩' THEN '唐'
      WHEN '宕' THEN '唐'
      WHEN '庚' THEN '庚'
      WHEN '梗' THEN '庚'
      WHEN '映' THEN '庚'
      WHEN '耕' THEN '耕'
      WHEN '耿' THEN '耕'
      WHEN '諍' THEN '耕'
      WHEN '清' THEN '清'
      WHEN '靜' THEN '清'
      WHEN '勁' THEN '清'
      WHEN '青' THEN '青'
      WHEN '迥' THEN '青'
      WHEN '徑' THEN '青'
      WHEN '蒸' THEN '蒸'
      WHEN '拯' THEN '蒸'
      WHEN '證' THEN '蒸'
      WHEN '登' THEN '登'
      WHEN '等' THEN '登'
      WHEN '嶝' THEN '登'
      WHEN '尤' THEN '尤'
      WHEN '有' THEN '尤'
      WHEN '宥' THEN '尤'
      WHEN '侯' THEN '侯'
      WHEN '厚' THEN '侯'
      WHEN '候' THEN '侯'
      WHEN '幽' THEN '幽'
      WHEN '黝' THEN '幽'
      WHEN '幼' THEN '幽'
      WHEN '侵' THEN '侵'
      WHEN '寑' THEN '侵'
      WHEN '沁' THEN '侵'
      WHEN '覃' THEN '覃'
      WHEN '感' THEN '覃'
      WHEN '勘' THEN '覃'
      WHEN '談' THEN '談'
      WHEN '敢' THEN '談'
      WHEN '闞' THEN '談'
      WHEN '鹽' THEN '鹽'
      WHEN '琰' THEN '鹽'
      WHEN '豔' THEN '鹽'
      WHEN '添' THEN '添'
      WHEN '忝' THEN '添'
      WHEN '㮇' THEN '添'
      WHEN '咸' THEN '咸'
      WHEN '豏' THEN '咸'
      WHEN '陷' THEN '咸'
      WHEN '銜' THEN '銜'
      WHEN '檻' THEN '銜'
      WHEN '鑑' THEN '銜'
      WHEN '嚴' THEN '嚴'
      WHEN '儼' THEN '嚴'
      WHEN '釅' THEN '嚴'
      WHEN '凡' THEN '凡'
      WHEN '范' THEN '凡'
      WHEN '梵' THEN '凡'
      WHEN '屋' THEN '屋'
      WHEN '沃' THEN '沃'
      WHEN '燭' THEN '燭'
      WHEN '覺' THEN '覺'
      WHEN '質' THEN '質'
      WHEN '術' THEN '術'
      WHEN '櫛' THEN '櫛'
      WHEN '物' THEN '物'
      WHEN '迄' THEN '迄'
      WHEN '月' THEN '月'
      WHEN '沒' THEN '沒'
      WHEN '曷' THEN '曷'
      WHEN '末' THEN '末'
      WHEN '鎋' THEN '鎋'
      WHEN '黠' THEN '黠'
      WHEN '屑' THEN '屑'
      WHEN '薛' THEN '薛'
      WHEN '藥' THEN '藥'
      WHEN '鐸' THEN '鐸'
      WHEN '陌' THEN '陌'
      WHEN '麥' THEN '麥'
      WHEN '昔' THEN '昔'
      WHEN '錫' THEN '錫'
      WHEN '職' THEN '職'
      WHEN '德' THEN '德'
      WHEN '緝' THEN '緝'
      WHEN '合' THEN '合'
      WHEN '盍' THEN '盍'
      WHEN '葉' THEN '葉'
      WHEN '怗' THEN '怗'
      WHEN '洽' THEN '洽'
      WHEN '狎' THEN '狎'
      WHEN '業' THEN '業'
      WHEN '乏' THEN '乏'
      ELSE NULL
    END AS 'rhyme_pq'
  , CASE rhyme.name
      WHEN '東' THEN '東'
      WHEN '董' THEN '東'
      WHEN '送' THEN '東'
      WHEN '屋' THEN '東'
      WHEN '冬' THEN '冬'
      WHEN '宋' THEN '冬'
      WHEN '沃' THEN '冬'
      WHEN '鍾' THEN '鍾'
      WHEN '腫' THEN '鍾'
      WHEN '用' THEN '鍾'
      WHEN '燭' THEN '鍾'
      WHEN '江' THEN '江'
      WHEN '講' THEN '江'
      WHEN '絳' THEN '江'
      WHEN '覺' THEN '江'
      WHEN '支' THEN '支'
      WHEN '紙' THEN '支'
      WHEN '寘' THEN '支'
      WHEN '脂' THEN '脂'
      WHEN '旨' THEN '脂'
      WHEN '至' THEN '脂'
      WHEN '之' THEN '之'
      WHEN '止' THEN '之'
      WHEN '志' THEN '之'
      WHEN '微' THEN '微'
      WHEN '尾' THEN '微'
      WHEN '未' THEN '微'
      WHEN '魚' THEN '魚'
      WHEN '語' THEN '魚'
      WHEN '御' THEN '魚'
      WHEN '虞' THEN '虞'
      WHEN '麌' THEN '虞'
      WHEN '遇' THEN '虞'
      WHEN '模' THEN '模'
      WHEN '姥' THEN '模'
      WHEN '暮' THEN '模'
      WHEN '齊' THEN '齊'
      WHEN '薺' THEN '齊'
      WHEN '霽' THEN '齊'
      WHEN '祭' THEN '祭'
      WHEN '泰' THEN '泰'
      WHEN '佳' THEN '佳'
      WHEN '蟹' THEN '佳'
      WHEN '卦' THEN '佳'
      WHEN '皆' THEN '皆'
      WHEN '駭' THEN '皆'
      WHEN '怪' THEN '皆'
      WHEN '夬' THEN '夬'
      WHEN '灰' THEN '灰'
      WHEN '賄' THEN '灰'
      WHEN '隊' THEN '灰'
      WHEN '咍' THEN '咍'
      WHEN '海' THEN '咍'
      WHEN '代' THEN '咍'
      WHEN '廢' THEN '廢'
      WHEN '真' THEN '真'
      WHEN '軫' THEN '真'
      WHEN '震' THEN '真'
      WHEN '質' THEN '真'
      WHEN '諄' THEN '諄'
      WHEN '準' THEN '諄'
      WHEN '稕' THEN '諄'
      WHEN '術' THEN '諄'
      WHEN '臻' THEN '臻'
      WHEN '櫛' THEN '臻'
      WHEN '文' THEN '文'
      WHEN '吻' THEN '文'
      WHEN '問' THEN '文'
      WHEN '物' THEN '文'
      WHEN '欣' THEN '欣'
      WHEN '隱' THEN '欣'
      WHEN '焮' THEN '欣'
      WHEN '迄' THEN '欣'
      WHEN '元' THEN '元'
      WHEN '阮' THEN '元'
      WHEN '願' THEN '元'
      WHEN '月' THEN '元'
      WHEN '魂' THEN '魂'
      WHEN '混' THEN '魂'
      WHEN '慁' THEN '魂'
      WHEN '沒' THEN '魂'
      WHEN '痕' THEN '痕'
      WHEN '很' THEN '痕'
      WHEN '恨' THEN '痕'
      WHEN '寒' THEN '寒'
      WHEN '旱' THEN '寒'
      WHEN '翰' THEN '寒'
      WHEN '曷' THEN '寒'
      WHEN '桓' THEN '桓'
      WHEN '緩' THEN '桓'
      WHEN '換' THEN '桓'
      WHEN '末' THEN '桓'
      WHEN '刪' THEN '刪'
      WHEN '潸' THEN '刪'
      WHEN '諫' THEN '刪'
      WHEN '鎋' THEN '刪'
      WHEN '山' THEN '山'
      WHEN '產' THEN '山'
      WHEN '襇' THEN '山'
      WHEN '黠' THEN '山'
      WHEN '先' THEN '先'
      WHEN '銑' THEN '先'
      WHEN '霰' THEN '先'
      WHEN '屑' THEN '先'
      WHEN '仙' THEN '仙'
      WHEN '獮' THEN '仙'
      WHEN '線' THEN '仙'
      WHEN '薛' THEN '仙'
      WHEN '蕭' THEN '蕭'
      WHEN '篠' THEN '蕭'
      WHEN '嘯' THEN '蕭'
      WHEN '宵' THEN '宵'
      WHEN '小' THEN '宵'
      WHEN '笑' THEN '宵'
      WHEN '肴' THEN '肴'
      WHEN '巧' THEN '肴'
      WHEN '效' THEN '肴'
      WHEN '豪' THEN '豪'
      WHEN '晧' THEN '豪'
      WHEN '号' THEN '豪'
      WHEN '歌' THEN '歌'
      WHEN '哿' THEN '歌'
      WHEN '箇' THEN '歌'
      WHEN '戈' THEN '戈'
      WHEN '果' THEN '戈'
      WHEN '過' THEN '戈'
      WHEN '麻' THEN '麻'
      WHEN '馬' THEN '麻'
      WHEN '禡' THEN '麻'
      WHEN '陽' THEN '陽'
      WHEN '養' THEN '陽'
      WHEN '漾' THEN '陽'
      WHEN '藥' THEN '陽'
      WHEN '唐' THEN '唐'
      WHEN '蕩' THEN '唐'
      WHEN '宕' THEN '唐'
      WHEN '鐸' THEN '唐'
      WHEN '庚' THEN '庚'
      WHEN '梗' THEN '庚'
      WHEN '映' THEN '庚'
      WHEN '陌' THEN '庚'
      WHEN '耕' THEN '耕'
      WHEN '耿' THEN '耕'
      WHEN '諍' THEN '耕'
      WHEN '麥' THEN '耕'
      WHEN '清' THEN '清'
      WHEN '靜' THEN '清'
      WHEN '勁' THEN '清'
      WHEN '昔' THEN '清'
      WHEN '青' THEN '青'
      WHEN '迥' THEN '青'
      WHEN '徑' THEN '青'
      WHEN '錫' THEN '青'
      WHEN '蒸' THEN '蒸'
      WHEN '拯' THEN '蒸'
      WHEN '證' THEN '蒸'
      WHEN '職' THEN '蒸'
      WHEN '登' THEN '登'
      WHEN '等' THEN '登'
      WHEN '嶝' THEN '登'
      WHEN '德' THEN '登'
      WHEN '尤' THEN '尤'
      WHEN '有' THEN '尤'
      WHEN '宥' THEN '尤'
      WHEN '侯' THEN '侯'
      WHEN '厚' THEN '侯'
      WHEN '候' THEN '侯'
      WHEN '幽' THEN '幽'
      WHEN '黝' THEN '幽'
      WHEN '幼' THEN '幽'
      WHEN '侵' THEN '侵'
      WHEN '寑' THEN '侵'
      WHEN '沁' THEN '侵'
      WHEN '緝' THEN '侵'
      WHEN '覃' THEN '覃'
      WHEN '感' THEN '覃'
      WHEN '勘' THEN '覃'
      WHEN '合' THEN '覃'
      WHEN '談' THEN '談'
      WHEN '敢' THEN '談'
      WHEN '闞' THEN '談'
      WHEN '盍' THEN '談'
      WHEN '鹽' THEN '鹽'
      WHEN '琰' THEN '鹽'
      WHEN '豔' THEN '鹽'
      WHEN '葉' THEN '鹽'
      WHEN '添' THEN '添'
      WHEN '忝' THEN '添'
      WHEN '㮇' THEN '添'
      WHEN '怗' THEN '添'
      WHEN '咸' THEN '咸'
      WHEN '豏' THEN '咸'
      WHEN '陷' THEN '咸'
      WHEN '洽' THEN '咸'
      WHEN '銜' THEN '銜'
      WHEN '檻' THEN '銜'
      WHEN '鑑' THEN '銜'
      WHEN '狎' THEN '銜'
      WHEN '嚴' THEN '嚴'
      WHEN '儼' THEN '嚴'
      WHEN '釅' THEN '嚴'
      WHEN '業' THEN '嚴'
      WHEN '凡' THEN '凡'
      WHEN '范' THEN '凡'
      WHEN '梵' THEN '凡'
      WHEN '乏' THEN '凡'
      ELSE NULL
    END AS 'rhyme_pqr'
  , initial AS 'initial'
  , CASE initial
      WHEN '幫' THEN '幫'
      WHEN '滂' THEN '幫'
      WHEN '並' THEN '幫'
      WHEN '明' THEN '幫'
      WHEN '端' THEN '端'
      WHEN '透' THEN '端'
      WHEN '定' THEN '端'
      WHEN '泥' THEN '端'
      WHEN '來' THEN '端'
      WHEN '知' THEN '知'
      WHEN '徹' THEN '知'
      WHEN '澄' THEN '知'
      WHEN '娘' THEN '知'
      WHEN '精' THEN '精'
      WHEN '清' THEN '精'
      WHEN '從' THEN '精'
      WHEN '心' THEN '精'
      WHEN '邪' THEN '精'
      WHEN '莊' THEN '莊'
      WHEN '初' THEN '莊'
      WHEN '崇' THEN '莊'
      WHEN '生' THEN '莊'
      WHEN '俟' THEN '莊'
      WHEN '章' THEN '章'
      WHEN '昌' THEN '章'
      WHEN '船' THEN '章'
      WHEN '書' THEN '章'
      WHEN '常' THEN '章'
      WHEN '日' THEN '章'
      WHEN '見' THEN '見'
      WHEN '溪' THEN '見'
      WHEN '群' THEN '見'
      WHEN '疑' THEN '見'
      WHEN '影' THEN '影'
      WHEN '曉' THEN '影'
      WHEN '匣' THEN '影'
      WHEN '云' THEN '影'
      WHEN '以' THEN '影'
      ELSE NULL
    END AS 'group'
  , CASE initial
      WHEN '幫' THEN '脣'
      WHEN '滂' THEN '脣'
      WHEN '並' THEN '脣'
      WHEN '明' THEN '脣'
      WHEN '端' THEN '舌'
      WHEN '透' THEN '舌'
      WHEN '定' THEN '舌'
      WHEN '泥' THEN '舌'
      WHEN '知' THEN '舌'
      WHEN '徹' THEN '舌'
      WHEN '澄' THEN '舌'
      WHEN '娘' THEN '舌'
      WHEN '來' THEN '舌'
      WHEN '精' THEN '齒'
      WHEN '清' THEN '齒'
      WHEN '從' THEN '齒'
      WHEN '心' THEN '齒'
      WHEN '邪' THEN '齒'
      WHEN '莊' THEN '齒'
      WHEN '初' THEN '齒'
      WHEN '崇' THEN '齒'
      WHEN '生' THEN '齒'
      WHEN '俟' THEN '齒'
      WHEN '章' THEN '齒'
      WHEN '昌' THEN '齒'
      WHEN '船' THEN '齒'
      WHEN '書' THEN '齒'
      WHEN '常' THEN '齒'
      WHEN '日' THEN '齒'
      WHEN '見' THEN '牙'
      WHEN '溪' THEN '牙'
      WHEN '群' THEN '牙'
      WHEN '疑' THEN '牙'
      WHEN '影' THEN '喉'
      WHEN '曉' THEN '喉'
      WHEN '匣' THEN '喉'
      WHEN '云' THEN '喉'
      WHEN '以' THEN '喉'
      ELSE NULL
    END AS 'place'
  , rounding
  , CASE rounding
      WHEN 'O' THEN '開'
      ELSE '合'
    END AS 'rounding_han'
  , division
  , CASE division
      WHEN '1' THEN '一'
      WHEN '2' THEN '二'
      WHEN '3' THEN '三'
      ELSE '四'
    END AS 'division_han'
  , upper_char
  , lower_char
  , upper_char || lower_char || '切' AS 'fanqie'
  FROM rhyme
    INNER JOIN small_rhyme
      ON rhyme.id = of_rhyme
);''')

cur.close()
conn.commit()
conn.close()
