name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Build
      run: |
        python build.py
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: qieyun.sqlite3
        path: qieyun.sqlite3
